int initialLatticeStruct(latticeStruct *,  int);
int lattice_connectivity();
int lattice_connectivity_pbc();
void print_and_exit(char *, ...);
int check_bond_mat();
int bonds(FILE *);
int generate_dihedrals();
int generate_dihedrals_test();
int generate_dihedrals_pbc();
int out_dihedrals(FILE *);
int particle_typeid();
int out_typeId(FILE *);
