//double* cross_product(double[],double[]);
//double bending_energy();
//double bond_harmonic_energy();
//double bond_length (int ,int );
//double backbone_length(int);
double avg_hgt();
double avg_hgt_sq();
double get_LX();
double sum_fq2();
double sum_q2fq2();
double sum_fq2_1D();
double sum_q2fq2_1D();
int initialize_fq2();
int calculate_fq2();
int calculate_fq2_1D();
int avg_fq2(FILE *, int);
int avg_fq2_1D(FILE *, int);
//int sum_hgt_node();
//int avg_hgt_node(int);
//int hgt_profile();
//int avg_hgt_profile(FILE *,int);
//int width_hgt(int);
//int print_width(FILE *);
